title        = "Tekton Pipelines"
baseURL      = "https://tekton-dev.netlify.com"
disableKinds = ["taxonomy", "taxonomyTerm"]

[blackfriday]
hrefTargetBlank = true

[params]
favicon = "favicon.png"
subtitle = "A Kubernetes-native pipeline resource"
github = "https://github.com/tektoncd/pipeline"
info = """
The **Tekton Pipelines** project provides [Kubernetes](https://kubernetes.io)-style resources for declaring CI/CD-style pipelines.
"""
comingsoon = "This site is currently under construction. For more information on the Tekton Pipelines project in the meantime, check out the [GitHub org](https://github.com/tektoncd)."

[params.logos]
hero = "horizontal-color"

[params.fonts]
sansserif = "Franklin Gothic Heavy Regular"
